### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by yguarata** [madeinnordeste/Condicao-do-Mar#1]
teste

**Comment by madeinnordeste** [comment]
"Pérra" é essa?

**Comment by yguarata** [comment]
ahahahahah
tava testando o issue tracker do github prum lance do doutorado ;)

On Wed, Apr 4, 2012 at 3:16 PM, Luiz Alberto S. Ribeiro <
reply@reply.github.com

> wrote:
> 
> "Prra"  essa?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/madeinnordeste/Condicao-do-Mar/issues/1#issuecomment-4959618

## 

Yguarat C. Cavalcanti,
Doutorando do Centro de Informtica UFPE http://www.cin.ufpe.br
Analista de Desenvolvimento de Software do SERPRO http://www.serpro.gov.br
http://www.yguarata.com
http://yakasurf.appspot.com

**Comment by madeinnordeste** [comment]
:P

**Comment by atrefonas** [comment]
stop spamming with this b.s.
